[package]
name = "taskter"
version = "0.1.0"
edition = "2024"

 [dependencies]
 clap = { version = "4.5.4", features = ["derive"] }
 serde = { version = "1.0", features = ["derive"] }
 chrono = { version = "0.4", features = ["serde"] }
 anyhow = "1.0"
 serde_json = "1.0"
 ratatui = "0.26.1"
 crossterm = "0.27.0"

 [dev-dependencies]
 tempfile = "3"

[features]
tui = []
